site_name: Guiferviz's Blog
site_url: https://guiferviz.com/
site_author: guiferviz
copyright: Copyright © 1994-2022 by Guiferviz
repo_url: https://github.com/guiferviz/guiferviz.github.io
repo_name: Guiferviz's Blog
docs_dir: docs
strict: false

theme:
    name: material
    custom_dir: overrides
    logo: assets/images/logo.png
    favicon: assets/images/favicon.ico
    language: en
    features:
      - navigation.tabs
      - navigation.indexes  # Use index.md as section page.
      # - navigation.tabs.sticky  # Always show tabs.
      # - header.autohide
      # - navigation.sections  # Expand sections 1 level.
      #- content.code.annotate
      # - content.tabs.link
      # - navigation.expand
      # - navigation.instant
      # - navigation.top
      # - navigation.tracking
      # - search.highlight
      # - search.share
      # - search.suggest
      # - toc.follow
    palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
    - mkdocs-jupyter
    - pdf-export:
        enabled_if_env: ENABLE_PDF_EXPORT
    - tags:
        tags_file: tags.md
    - search

markdown_extensions:
    - meta
    # Code highlight.
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    # MathJax with some options in the extra_javascript.
    - pymdownx.arithmatex:
        generic: true
    # Mermaid plots.
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
    # Emoji.
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    # Task lists with checkboxes.
    - pymdownx.tasklist:
        custom_checkbox: true
    # Superfences admonition.
    - admonition
    - pymdownx.details

extra_javascript:
  # MathJax.
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # p5js
  - https://cdn.jsdelivr.net/npm/p5@1.4.1/lib/p5.js

extra:
  generator: false
  analytics:
    provider: google
    property: G-69CEMWCD5E
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/guiferviz
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/guiferviz
    - icon: fontawesome/brands/github
      link: https://github.com/guiferviz

# Page tree
nav:
    - Home: index.md
    - Best Practices:
      - best_practices/index.md
      - best_practices/when_to_stop_using_notebooks.md
      - best_practices/do_not_number_steps.md
    - Programming Problems:
      - problems/reservoir-sampling.md
      - problems/euler-phi-totient-function.md
    - Tags: tags.md
